Fix storing regex as string when cleaned
MycroftAI/adapt pull request #135
Opened 2021-06-23 07:47 UTC by forslund

The removing regexp changed the type of the member to a list instead of a set.

2021-06-23 14:47 UTC, clusterfudge commented
@forslund can you provide a little more color on what this does and why it matters? The fact that the only test change asserts this internal variable is a set seems strange to me.

2021-06-23 16:31 UTC, forslund commented
I can remove the test. It was mainly to prove to myself that the type remained `set()`.

The issue is that the `_regex_strings` member is a set at code and `.add()` is [called on it](https://github.com/MycroftAI/adapt/blob/master/adapt/engine.py#L160), the removal code was done using a list comprehension resulting in `_regex_strings() was a list after removal was called. a list doesn't have the `.add()` member so the issue in #134 happens.

2021-06-23 16:48 UTC, emphasize commented
just realized that with the new weather skill i'm also not able to get a location on `Message`, so this might be problematic elsewhere. Or is this related?

2021-06-23 17:04 UTC, j1nx commented
Tested the fix on OVOS with all latest and greatest packages (which had the same issue) and it solved the error.

2021-06-23 17:11 UTC, forslund commented
@emphasize this would hinder it after reloading the skill but should work on first startup.

2021-06-23 17:12 UTC, emphasize commented
yeah, tested it with the fix, but still no location on Message

2021-06-23 17:27 UTC, emphasize commented
The only meaningfull log i get is
```
2021-06-23 19:22:59.576 | DEBUG    | 21131 | mycroft.skills.skill_data:load_regex_from_file:64 | regex pre-munge: .*\b(bei|in) (?P<Location>(?!\bcelsius\b|\bfahrenheit\b) *.+)
2021-06-23 19:22:59.576 | DEBUG    | 21131 | mycroft.skills.skill_data:load_regex_from_file:66 | regex post-munge: .*\b(bei|in) (?P<skill_weather_emphasizeLocation>(?!\bcelsius\b|\bfahrenheit\b) *.+)
```

2021-06-23 17:35 UTC, emphasize commented
Nevermind, Chris has written `self.location = message.data.get("location")` instead of 
`self.location = message.data.get("Location")`

2021-06-23 18:29 UTC, clusterfudge requested changes
@forslund Since this is fixing a bug in the wild for which there is no test coverage, please add a test that verifies the behavior you're fixing. 

I'd recommend starting with one that reproduces #134 and then ensuring that your change fixes it.

2021-06-23 18:56 UTC, forslund commented
Absolutely will add that.

2021-06-23 19:32 UTC, forslund commented
Ok found another issue with this...since the tagger keeps a reference to the old regexp_entity this isn't actually working as intended...

2021-06-23 19:47 UTC, forslund commented
Added a fix along with a test for that issue as well.

2021-06-24 03:01 UTC, krisgesling reviewed
Nice thanks - working as expected for me also, and the tests look good.

I'll let Sean verify before we merge though

2021-06-24 03:44 UTC, clusterfudge reviewed
this lgtm to me now, last step is a PATCH version bump.

2021-06-24 05:28 UTC, forslund commented
Version bumped 0.0.1 units :)

2021-06-24 16:13 UTC, clusterfudge approved these changes

2021-06-24 18:39 UTC, merged